"""add post replies and soft deletion

Revision ID: 1301cf761d03
Revises: 0f3197e230a9
Create Date: 2026-10-05 21:04:47.301723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1301cf761d03'
down_revision: Union[str, Sequence[str], None] = '0f3197e230a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('parent_post_id', sa.Uuid(), nullable=True))
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_posts_parent_post_id_created_at', 'posts', ['parent_post_id', 'created_at'], unique=False, postgresql_where='parent_post_id IS NOT NULL')
    op.create_foreign_key(op.f('fk_posts_parent_post_id_posts'), 'posts', 'posts', ['parent_post_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
    # Added by hand: autogenerate does not detect check constraints.
    op.create_check_constraint(op.f('ck_posts_no_self_reply'), 'posts', 'parent_post_id != id')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_posts_no_self_reply'), 'posts', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_posts_parent_post_id_posts'), 'posts', type_='foreignkey')
    op.drop_index('ix_posts_parent_post_id_created_at', table_name='posts', postgresql_where='parent_post_id IS NOT NULL')
    op.drop_column('posts', 'deleted_at')
    op.drop_column('posts', 'parent_post_id')
    # ### end Alembic commands ###
