"""add rate limits

Revision ID: 7f984c985213
Revises: fce75e951291
Create Date: 2026-10-08 14:13:50.540025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f984c985213'
down_revision: Union[str, Sequence[str], None] = 'fce75e951291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.CheckConstraint('count >= 0', name=op.f('ck_rate_limits_count_not_negative')),
    sa.PrimaryKeyConstraint('key_hash', name=op.f('pk_rate_limits'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
