"""drop users is_private

Revision ID: fce75e951291
Revises: 1301cf761d03
Create Date: 2026-10-06 19:50:21.650915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce75e951291'
down_revision: Union[str, Sequence[str], None] = '1301cf761d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_private')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Adjusted by hand to the definition the column was created with in
    # 0b8c71c5bc0d. The values it held are gone: every account comes back
    # with the default, false.
    op.add_column('users', sa.Column('is_private', sa.Boolean(), server_default=sa.text('false'), nullable=False))
